name = "MatsubaraFunctions"
uuid = "3b93aed6-d40a-4520-b131-eee49889bcc0"
authors = ["Dominik Kiese <dkiese1308.physik@gmail.com>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
